// This file is auto-generated by vite/UpdateTheme.ts. Do not edit manually.

export const themeColorNames = [
	"primary",
	"onprimary",
	"secondary",
	"onsecondary",
	"success",
	"info",
	"warning",
	"danger",
	"surface",
	"surface2",
	"surface3",
	"surface4",
	"onsurface",
	"onsurface2",
	"surfacehighlight",
	"oncolor"
];
