/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    AutocompleteTextArea: typeof import('./src/components/ui/AutocompleteTextArea.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ChatContent: typeof import('./src/components/ui/ChatContent.vue')['default']
    Chip: typeof import('./src/components/ui/Chip.vue')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ColorPickerPop: typeof import('./src/components/ui/ColorPickerPop.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    DataTable2: typeof import('./src/components/ui/DataTable2.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    DragDropFileInput: typeof import('./src/components/ui/DragDropFileInput.vue')['default']
    Draggable: typeof import('./src/components/ui/Draggable.vue')['default']
    Drawer: typeof import('./src/components/ui/Drawer.vue')['default']
    FileInput: typeof import('./src/components/ui/FileInput.vue')['default']
    FlexScroll: typeof import('./src/components/ui/FlexScroll.vue')['default']
    GlobalTooltip: typeof import('./src/components/ui/GlobalTooltip.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    IconSelector: typeof import('./src/components/ui/IconSelector.vue')['default']
    LanguageSwitch: typeof import('./src/components/ui/LanguageSwitch.vue')['default']
    LightSwitch: typeof import('./src/components/ui/LightSwitch.vue')['default']
    Menu: typeof import('./src/components/ui/Menu.vue')['default']
    PathButton: typeof import('./src/components/ui/PathButton.vue')['default']
    PopNotification: typeof import('./src/components/ui/PopNotification.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    Rating: typeof import('./src/components/ui/Rating.vue')['default']
    Resizable: typeof import('./src/components/ui/Resizable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SimpleColorPicker: typeof import('./src/components/ui/SimpleColorPicker.vue')['default']
    Slider: typeof import('./src/components/ui/Slider.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    Stepper: typeof import('./src/components/ui/Stepper.vue')['default']
    TagInput: typeof import('./src/components/ui/TagInput.vue')['default']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
    TextArea: typeof import('./src/components/ui/TextArea.vue')['default']
    TextField: typeof import('./src/components/ui/TextField.vue')['default']
    Toggle: typeof import('./src/components/ui/Toggle.vue')['default']
    ToolBar: typeof import('./src/components/ui/ToolBar.vue')['default']
    ToolBarButton: typeof import('./src/components/ui/ToolBarButton.vue')['default']
    TreeView: typeof import('./src/components/ui/TreeView.vue')['default']
  }
}
