import * as fs from "fs";

export function GetFileText(path: string)
{
	const content = fs.readFileSync(path, "utf8");
	console.log(content);
	return content;
}

(async function ()
{
	let cssContent = GetFileText("./src/themes/theme.css");

	const rootRegex = /:root\s*{([^}]+)}/s;
	const rootMatch = cssContent.match(rootRegex);

	if (rootMatch)
	{
		const rootContent = rootMatch[1];
		const varRegex = /--([a-zA-Z0-9-]+)\s*:/g;
		const themeNames: string[] = [];
		let match;
		while ((match = varRegex.exec(rootContent)) !== null)
		{
			themeNames.push(match[1]);
		}

		const fileContent = `// This file is auto-generated by vite/UpdateTheme.ts. Do not edit manually.

export const themeColorNames = ${JSON.stringify(themeNames, null, "\t")};
`;

		fs.writeFileSync("./src/themes/themeNames.ts", fileContent, "utf8");
		console.log("Updated src/themes/themeNames.ts");
	}

	console.log(cssContent);

})().catch(err =>
{
	console.error(err);
});
